import './globals.css'
import { Poppins } from 'next/font/google'
import Nav from '../components/nav'
import Footer from '../components/footer'

const poppins = Poppins({
  weight: '300',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
